export interface Spell {
  id: string;
  name: string;
  school: string;
  level: string;
  cooldown: string;
  mana: string;
  castType: string;
  rarity: string;
  uniqueInfo: string[];
  description: string;
  imageUrl: string;
}

export interface SpellSchool {
  name: string;
  color: string;
  spells: Spell[];
}

const schoolColors: Record<string, string> = {
  Blood: "hsl(0 70% 35%)",
  Eldritch: "hsl(270 60% 40%)",
  Ender: "hsl(280 50% 35%)",
  Evocation: "hsl(45 80% 45%)",
  Fire: "hsl(15 85% 50%)",
  Holy: "hsl(45 90% 65%)",
  Ice: "hsl(200 70% 55%)",
  Lightning: "hsl(55 90% 55%)",
  Nature: "hsl(120 50% 35%)",
};

function toSlug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, "");
}

export const spellSchools: SpellSchool[] = [
  {
    name: "Blood",
    color: schoolColors.Blood,
    spells: [
      {
        id: "acupuncture",
        name: "Acupuncture",
        school: "Blood",
        level: "1 to 10",
        cooldown: "20s",
        mana: "25 to 70",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["2 Damage", "5-14 Projectiles"],
        description: "Around a targeted creature, create a field of blood needles in every direction, shooting down and healing you for 25% of damage done",
        imageUrl: "https://iron.wiki/img/spells/acupuncture.png",
      },
      {
        id: "blood_needles",
        name: "Blood Needles",
        school: "Blood",
        level: "1 to 10",
        cooldown: "10s",
        mana: "25 to 70",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["2-4.25 Damage", "5 Projectiles"],
        description: "Create a ring of needles made from blood and fire them forward, skewering targets and healing you for 25% of damage done",
        imageUrl: "https://iron.wiki/img/spells/blood_needles.png",
      },
      {
        id: "blood_slash",
        name: "Blood Slash",
        school: "Blood",
        level: "1 to 5",
        cooldown: "10s",
        mana: "25 to 45",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10-14 Damage"],
        description: "Slash forward to send out a concentrated blade of blood, slicing through creatures and healing for 15% of damage done.",
        imageUrl: "https://iron.wiki/img/spells/blood_slash.png",
      },
      {
        id: "blood_step",
        name: "Blood Step",
        school: "Blood",
        level: "1 to 5",
        cooldown: "12s",
        mana: "30 to 70",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["12-28 Block Range"],
        description: "Instantaneously teleport to where you are looking, or directly behind any targeted creature. Gain a short duration of true invisibility upon reaching your destination.",
        imageUrl: "https://iron.wiki/img/spells/blood_step.png",
      },
      {
        id: "devour",
        name: "Devour",
        school: "Blood",
        level: "1 to 10",
        cooldown: "20s",
        mana: "25 to 61",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["6-15 Damage", "2-6 Max HP on Kill"],
        description: "Pull in a nearby creature and attack them with a bite, leeching 15% of damage done as health. If the creature is killed, you temporarily gain additional max HP.",
        imageUrl: "https://iron.wiki/img/spells/devour.png",
      },
      {
        id: "heartstop",
        name: "Heartstop",
        school: "Blood",
        level: "1 to 5",
        cooldown: "120s",
        mana: "100 to 140",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10s-16s Effect Length"],
        description: "Cast to inflict yourself with Heartstop, an effect that makes you temporarily invulnerable. However, once it wears off, you take 50% of all damage accumulated while under its effects.",
        imageUrl: "https://iron.wiki/img/spells/heartstop.png",
      },
      {
        id: "raise_dead",
        name: "Raise Dead",
        school: "Blood",
        level: "1 to 6",
        cooldown: "150s",
        mana: "50 to 100",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["3-8 Summons"],
        description: "Cast to summon undead minions from the earth beneath you. The higher the power, the better equipment they will have.",
        imageUrl: "https://iron.wiki/img/spells/raise_dead.png",
      },
      {
        id: "ray_of_siphoning",
        name: "Ray Of Siphoning",
        school: "Blood",
        level: "1 to 10",
        cooldown: "15s",
        mana: "8 to 17",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1-3.25 Damage", "12 Block Range"],
        description: "Hold to cast a ray of necrotic energy that siphons health from creatures it hits, damaging them and healing you for 100% of damage done.",
        imageUrl: "https://iron.wiki/img/spells/ray_of_siphoning.png",
      },
      {
        id: "sacrifice",
        name: "Sacrifice",
        school: "Blood",
        level: "1 to 5",
        cooldown: "1s",
        mana: "25 to 45",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["12-16 Base Damage", "3 Block Radius"],
        description: "Target one of your magic summons to cause them to explode, killing them instantly, and dealing large damage in the area around them.",
        imageUrl: "https://iron.wiki/img/spells/sacrifice.png",
      },
      {
        id: "wither_skull",
        name: "Wither Skull",
        school: "Blood",
        level: "1 to 10",
        cooldown: "1s",
        mana: "20 to 38",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Launch a wither skull forward that explodes in a small radius around the impact. The higher the level, the faster the projectile.",
        imageUrl: "https://iron.wiki/img/spells/wither_skull.png",
      },
    ],
  },
  {
    name: "Eldritch",
    color: schoolColors.Eldritch,
    spells: [
      {
        id: "abyssal_shroud",
        name: "Abyssal Shroud",
        school: "Eldritch",
        level: "1 to 3",
        cooldown: "200s",
        mana: "300 to 340",
        castType: "Instant",
        rarity: "Legendary",
        uniqueInfo: ["6s-18s Effect Length"],
        description: "Cloak yourself with the shadows of the abyss, granting the ability to evade any attack for a short duration of time.",
        imageUrl: "https://iron.wiki/img/spells/abyssal_shroud.png",
      },
      {
        id: "eldritch_blast",
        name: "Eldritch Blast",
        school: "Eldritch",
        level: "1 to 5",
        cooldown: "15s",
        mana: "90 to 150",
        castType: "Instant",
        rarity: "Legendary",
        uniqueInfo: ["15 Damage", "3-7 Blasts", "30 Block Range"],
        description: "Fire rays of pure, devastating energy.",
        imageUrl: "https://iron.wiki/img/spells/eldritch_blast.png",
      },
      {
        id: "planar_sight",
        name: "Planar Sight",
        school: "Eldritch",
        level: "1 to 3",
        cooldown: "200s",
        mana: "150 to 250",
        castType: "Instant",
        rarity: "Legendary",
        uniqueInfo: ["40s-1.3m Effect Length"],
        description: "Shift your vision in between planes, gaining the ability to see creatures through solid material.",
        imageUrl: "https://iron.wiki/img/spells/planar_sight.png",
      },
      {
        id: "pocket_dimension",
        name: "Pocket Dimension",
        school: "Eldritch",
        level: "1",
        cooldown: "60s",
        mana: "300",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: [],
        description: "Cast to transport yourself into a personal pocket dimension only you can access, giving a small free range area.",
        imageUrl: "https://iron.wiki/img/spells/pocket_dimension.png",
      },
      {
        id: "sculk_tentacles",
        name: "Sculk Tentacles",
        school: "Eldritch",
        level: "1 to 4",
        cooldown: "30s",
        mana: "150 to 300",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: ["8 Damage", "2.5-6.5 Block Radius"],
        description: "From where you look, erupt a mass of sculk energy in the form of wailing tentacles, damaging and blinding creatures caught in the chaos.",
        imageUrl: "https://iron.wiki/img/spells/sculk_tentacles.png",
      },
      {
        id: "sonic_boom",
        name: "Sonic Boom",
        school: "Eldritch",
        level: "1 to 3",
        cooldown: "25s",
        mana: "110 to 210",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: ["20-36 Damage", "20-30 Block Range"],
        description: "Blast forth a sonic boom of immense power, passing through solid material and harming all creatures in its path.",
        imageUrl: "https://iron.wiki/img/spells/sonic_boom.png",
      },
      {
        id: "telekinesis",
        name: "Telekinesis",
        school: "Eldritch",
        level: "1 to 5",
        cooldown: "35s",
        mana: "25",
        castType: "Continuous",
        rarity: "Legendary",
        uniqueInfo: ["12-20 Block Range"],
        description: "Reach out with a spectral force and grip a creature, forcing them towards your gaze. Creatures are susceptible to kinetic damage.",
        imageUrl: "https://iron.wiki/img/spells/telekinesis.png",
      },
    ],
  },
  {
    name: "Ender",
    color: schoolColors.Ender,
    spells: [
      {
        id: "black_hole",
        name: "Black Hole",
        school: "Ender",
        level: "1 to 6",
        cooldown: "120s",
        mana: "300 to 800",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: ["2 AOE Damage", "6.1-16.1 Block Radius"],
        description: "Around a targeted location, create a fissure into the void, manifesting a black hole that will suck in nearby creatures and slowly crush them to death.",
        imageUrl: "https://iron.wiki/img/spells/black_hole.png",
      },
      {
        id: "counterspell",
        name: "Counterspell",
        school: "Ender",
        level: "1",
        cooldown: "10s",
        mana: "50",
        castType: "Instant",
        rarity: "Rare",
        uniqueInfo: ["Interrupt casting", "Banish summons"],
        description: "Interrupt player and mob casting. Banishes summoned creatures and removes mob effects like fortify or evasion.",
        imageUrl: "https://iron.wiki/img/spells/counterspell.png",
      },
      {
        id: "dragon_breath",
        name: "Dragon Breath",
        school: "Ender",
        level: "1 to 10",
        cooldown: "12s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1.75-8.5 Damage"],
        description: "Hold to spew a cone of dragon breath forwards. Each time a creature is hit, there is a chance to create a pool of dragon breath at their feet.",
        imageUrl: "https://iron.wiki/img/spells/dragon_breath.png",
      },
      {
        id: "echoing_strikes",
        name: "Echoing Strikes",
        school: "Ender",
        level: "1 to 5",
        cooldown: "60s",
        mana: "50 to 90",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["30%-70% Damage", "2.0 Block Radius", "20s-40s Effect"],
        description: "While under the effects of the spell, non-magical attacks will leave an echo of ender energy behind, shortly thereafter exploding with an echo of the original attack's damage.",
        imageUrl: "https://iron.wiki/img/spells/echoing_strikes.png",
      },
      {
        id: "evasion",
        name: "Evasion",
        school: "Ender",
        level: "1 to 5",
        cooldown: "180s",
        mana: "40 to 120",
        castType: "Instant",
        rarity: "Epic to Legendary",
        uniqueInfo: ["1-5 Hits Dodged"],
        description: "Cast to imbue yourself with ender energy. Upon being attacked while under its effects, you will immediately teleport within a short radius and avoid taking any damage.",
        imageUrl: "https://iron.wiki/img/spells/evasion.png",
      },
      {
        id: "magic_arrow",
        name: "Magic Arrow",
        school: "Ender",
        level: "1 to 10",
        cooldown: "8s",
        mana: "40 to 85",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10-28 Damage"],
        description: "Hold to charge a piercing arrow made of arcane energy. This arrow has no gravity and can travel through blocks.",
        imageUrl: "https://iron.wiki/img/spells/magic_arrow.png",
      },
      {
        id: "magic_missile",
        name: "Magic Missile",
        school: "Ender",
        level: "1 to 10",
        cooldown: "1s",
        mana: "10 to 28",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Shoot a bolt of concentrated arcane magic. Also a trademark of every wizard.",
        imageUrl: "https://iron.wiki/img/spells/magic_missile.png",
      },
      {
        id: "portal",
        name: "Portal",
        school: "Ender",
        level: "1 to 3",
        cooldown: "180s",
        mana: "200 to 220",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["48 Cast Range", "5m-9m Portal Duration"],
        description: "Creates two portals that allows players to travel back and forth between them.",
        imageUrl: "https://iron.wiki/img/spells/portal.png",
      },
      {
        id: "recall",
        name: "Recall",
        school: "Ender",
        level: "1",
        cooldown: "300s",
        mana: "100",
        castType: "Long",
        rarity: "Uncommon",
        uniqueInfo: [],
        description: "Warps you back to your spawn location, or world spawn if there is none.",
        imageUrl: "https://iron.wiki/img/spells/recall.png",
      },
      {
        id: "shadow_slash",
        name: "Shadow Slash",
        school: "Ender",
        level: "1 to 5",
        cooldown: "15s",
        mana: "30 to 90",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["5.0-9.0 Damage"],
        description: "Dash forward with an arcing slash of arcane energy, striking creatures in an area. Projectiles hit are deflected. Scales off held weapon's melee damage and enchantments.",
        imageUrl: "https://iron.wiki/img/spells/shadow_slash.png",
      },
      {
        id: "starfall",
        name: "Starfall",
        school: "Ender",
        level: "1 to 10",
        cooldown: "16s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["4-8.5 Damage", "6 Block Radius"],
        description: "Target a single area and continuously rain down arcane comets from above for the duration of the spell.",
        imageUrl: "https://iron.wiki/img/spells/starfall.png",
      },
      {
        id: "summon_ender_chest",
        name: "Summon Ender Chest",
        school: "Ender",
        level: "1",
        cooldown: "5s",
        mana: "25",
        castType: "Instant",
        rarity: "Rare",
        uniqueInfo: [],
        description: "Apparate your Ender Chest inventory upon casting.",
        imageUrl: "https://iron.wiki/img/spells/summon_ender_chest.png",
      },
      {
        id: "summon_swords",
        name: "Summon Swords",
        school: "Ender",
        level: "1 to 5",
        cooldown: "150s",
        mana: "80 to 140",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["3 Summons", "100%-140% Damage", "100%-180% Health"],
        description: "Conjure a trio of spectral armaments to aid in battle: a brawling shortsword, a quick rapier, and a tanking claymore.",
        imageUrl: "https://iron.wiki/img/spells/summon_swords.png",
      },
      {
        id: "teleport",
        name: "Teleport",
        school: "Ender",
        level: "1 to 5",
        cooldown: "3s",
        mana: "20 to 40",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["10-50 Block Range"],
        description: "Instantaneously teleport to where you are looking, leaving nothing but a cloud of ender energy behind.",
        imageUrl: "https://iron.wiki/img/spells/teleport.png",
      },
    ],
  },
  {
    name: "Evocation",
    color: schoolColors.Evocation,
    spells: [
      {
        id: "arrow_volley",
        name: "Arrow Volley",
        school: "Evocation",
        level: "1 to 6",
        cooldown: "15s",
        mana: "40 to 90",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["2 Damage", "25-80 Projectiles"],
        description: "Around a targeted creature or block, summon a rolling wave of magical arrows from the sky.",
        imageUrl: "https://iron.wiki/img/spells/arrow_volley.png",
      },
      {
        id: "chain_creeper",
        name: "Chain Creeper",
        school: "Evocation",
        level: "1 to 6",
        cooldown: "15s",
        mana: "40 to 90",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["5 Damage", "3-8 Projectiles"],
        description: "Around a targeted creature or block, conjure a ring of creeper heads that falls to the ground and explodes. This can chain multiple times.",
        imageUrl: "https://iron.wiki/img/spells/chain_creeper.png",
      },
      {
        id: "fang_strike",
        name: "Fang Strike",
        school: "Evocation",
        level: "1 to 10",
        cooldown: "5s",
        mana: "30 to 57",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["8-17 Fangs", "6-15 Damage"],
        description: "Conjure a line of evoker fangs in front of you, in classic illager fashion.",
        imageUrl: "https://iron.wiki/img/spells/fang_strike.png",
      },
      {
        id: "fang_ward",
        name: "Fang Ward",
        school: "Evocation",
        level: "1 to 8",
        cooldown: "15s",
        mana: "45 to 80",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["2-4 Rings", "8-15 Damage"],
        description: "Conjure protective rings of evoker fangs around you, in classic illager fashion.",
        imageUrl: "https://iron.wiki/img/spells/fang_ward.png",
      },
      {
        id: "firecracker",
        name: "Firecracker",
        school: "Evocation",
        level: "1 to 10",
        cooldown: "1s",
        mana: "20 to 38",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["4-13 Damage"],
        description: "Instantaneously conjure a firework where you look that explodes in a small radius around it.",
        imageUrl: "https://iron.wiki/img/spells/firecracker.png",
      },
      {
        id: "gust",
        name: "Gust",
        school: "Evocation",
        level: "1 to 10",
        cooldown: "12s",
        mana: "30 to 75",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["100%-190% Strength", "4.5-9 Impact Damage"],
        description: "Conjure a strong gust of wind, knocking back creatures in a conical shape, causing damage if they impact a wall.",
        imageUrl: "https://iron.wiki/img/spells/gust.png",
      },
      {
        id: "invisibility",
        name: "Invisibility",
        school: "Evocation",
        level: "1 to 6",
        cooldown: "45s",
        mana: "35 to 75",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10s-35s Effect Length"],
        description: "Cast to briefly grant yourself true invisibility, which hides armor and held items, but immediately wears off upon dealing damage.",
        imageUrl: "https://iron.wiki/img/spells/invisibility.png",
      },
      {
        id: "lob_creeper",
        name: "Lob Creeper",
        school: "Evocation",
        level: "1 to 10",
        cooldown: "2s",
        mana: "20 to 38",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Lob the head of a creeper forward that explodes in a medium radius around the impact.",
        imageUrl: "https://iron.wiki/img/spells/lob_creeper.png",
      },
      {
        id: "shield",
        name: "Shield",
        school: "Evocation",
        level: "1 to 10",
        cooldown: "8s",
        mana: "35 to 80",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["15-105 HP"],
        description: "Conjure a stationary shield of arcane energy where you look that will block projectiles and prevent creatures from passing.",
        imageUrl: "https://iron.wiki/img/spells/shield.png",
      },
      {
        id: "slow",
        name: "Slow",
        school: "Evocation",
        level: "1 to 4",
        cooldown: "80s",
        mana: "50 to 80",
        castType: "Long",
        rarity: "Epic to Legendary",
        uniqueInfo: ["10%-40% Slowed", "20s-32s Effect", "5 Max Targets"],
        description: "In a radius around a targeted creature, apply the Slowed effect to enemies, decreasing movement speed, attack speed, and mana regeneration.",
        imageUrl: "https://iron.wiki/img/spells/slow.png",
      },
      {
        id: "spectral_hammer",
        name: "Spectral Hammer",
        school: "Evocation",
        level: "1 to 5",
        cooldown: "2s",
        mana: "15 to 35",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["3x3x2", "16 Block Range"],
        description: "Conjure a spectral hammer that will mine all connected stone-type blocks in a cube where it hits, leaving only ores and rubble behind.",
        imageUrl: "https://iron.wiki/img/spells/spectral_hammer.png",
      },
      {
        id: "summon_horse",
        name: "Summon Horse",
        school: "Evocation",
        level: "1 to 5",
        cooldown: "20s",
        mana: "50 to 58",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: [],
        description: "Conjure a spectral steed that will follow you around and only let you ride. The horse's speed, health, and jump height scales with spell power.",
        imageUrl: "https://iron.wiki/img/spells/summon_horse.png",
      },
      {
        id: "summon_vex",
        name: "Summon Vex",
        school: "Evocation",
        level: "1 to 5",
        cooldown: "150s",
        mana: "50 to 90",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["3-7 Summons"],
        description: "Cast to conjure vexes that will follow, protect, and fight for you.",
        imageUrl: "https://iron.wiki/img/spells/summon_vex.png",
      },
      {
        id: "wololo",
        name: "Wololo",
        school: "Evocation",
        level: "1",
        cooldown: "10s",
        mana: "10",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: ["Wololo!"],
        description: "Wololo!",
        imageUrl: "https://iron.wiki/img/spells/wololo.png",
      },
    ],
  },
  {
    name: "Fire",
    color: schoolColors.Fire,
    spells: [
      {
        id: "blaze_storm",
        name: "Blaze Storm",
        school: "Fire",
        level: "1 to 10",
        cooldown: "20s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["2-5.59 Damage"],
        description: "Hold to unleash a barrage of blaze fireballs, shooting rapidly but wildly in front of you and igniting any creatures or blocks hit.",
        imageUrl: "https://iron.wiki/img/spells/blaze_storm.png",
      },
      {
        id: "burning_dash",
        name: "Burning Dash",
        school: "Fire",
        level: "1 to 10",
        cooldown: "10s",
        mana: "20 to 38",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-15 Damage"],
        description: "Quickly launch yourself forward in a haze of fire, searing creatures you pass through while in a blaze.",
        imageUrl: "https://iron.wiki/img/spells/burning_dash.png",
      },
      {
        id: "fire_arrow",
        name: "Fire Arrow",
        school: "Fire",
        level: "1 to 10",
        cooldown: "8s",
        mana: "40 to 85",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["11-20 Damage", "3 Block Radius", "5.5-10 AOE Damage"],
        description: "Aim an arrow made of fiery magic that will deal direct damage on impact and explode for half damage in a small radius around it.",
        imageUrl: "https://iron.wiki/img/spells/fire_arrow.png",
      },
      {
        id: "fire_breath",
        name: "Fire Breath",
        school: "Fire",
        level: "1 to 10",
        cooldown: "12s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1-7.75 Damage"],
        description: "Hold to spew a cone of fire outwards, igniting creatures and blocks in its path.",
        imageUrl: "https://iron.wiki/img/spells/fire_breath.png",
      },
      {
        id: "fireball",
        name: "Fireball",
        school: "Fire",
        level: "1 to 5",
        cooldown: "25s",
        mana: "60 to 120",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10-30 Damage", "3-7 Block Radius"],
        description: "Manifest and throw a ball of fire, exploding and dealing massive damage on impact.",
        imageUrl: "https://iron.wiki/img/spells/fireball.png",
      },
      {
        id: "firebolt",
        name: "Firebolt",
        school: "Fire",
        level: "1 to 10",
        cooldown: "1s",
        mana: "10 to 28",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Shoot a small projectile of fire, igniting whatever it hits.",
        imageUrl: "https://iron.wiki/img/spells/firebolt.png",
      },
      {
        id: "flaming_barrage",
        name: "Flaming Barrage",
        school: "Fire",
        level: "1 to 5",
        cooldown: "15s",
        mana: "80 to 100",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["3-11 Damage", "5 Projectiles"],
        description: "Cast to select targets, which at the end of recasting, will each be under barrage of small fireballs.",
        imageUrl: "https://iron.wiki/img/spells/flaming_barrage.png",
      },
      {
        id: "flaming_strike",
        name: "Flaming Strike",
        school: "Fire",
        level: "1 to 5",
        cooldown: "15s",
        mana: "30 to 90",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["5.0-13.0 Damage"],
        description: "Unleash a sweeping melee attack in the form of a wreath of flames. This spell is uninterruptible.",
        imageUrl: "https://iron.wiki/img/spells/flaming_strike.png",
      },
      {
        id: "heat_surge",
        name: "Heat Surge",
        school: "Fire",
        level: "1 to 6",
        cooldown: "45s",
        mana: "50 to 100",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["15%-40% Reduced Armor", "10s-20s Effect", "6.5-9 Block Radius"],
        description: "Emanate a surge of fiery magic, igniting and rending creatures in a radius around you. Rended creatures have reduced armor.",
        imageUrl: "https://iron.wiki/img/spells/heat_surge.png",
      },
      {
        id: "magma_bomb",
        name: "Magma Bomb",
        school: "Fire",
        level: "1 to 8",
        cooldown: "12s",
        mana: "30 to 65",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["8 Damage", "1.7-3.9 AOE Damage", "4 Block Radius"],
        description: "Launch a bomb made from magma, exploding on impact and leaving a field of fire where it lands.",
        imageUrl: "https://iron.wiki/img/spells/magma_bomb.png",
      },
      {
        id: "raise_hell",
        name: "Raise Hell",
        school: "Fire",
        level: "1 to 5",
        cooldown: "25s",
        mana: "90 to 270",
        castType: "Long",
        rarity: "Legendary",
        uniqueInfo: ["15.0 Damage", "8 Block Radius", "1-5 Casts"],
        description: "Slam down your weapon to wreath a fiery shockwave in a large radius around you. Damage scales based on the held weapon.",
        imageUrl: "https://iron.wiki/img/spells/raise_hell.png",
      },
      {
        id: "scorch",
        name: "Scorch",
        school: "Fire",
        level: "1 to 10",
        cooldown: "12s",
        mana: "50 to 95",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["8-17 Damage", "2.5 Block Radius"],
        description: "In a targeted area, erupt a scorch of fiery magic, damaging creatures in the zone and leaving a field of fire.",
        imageUrl: "https://iron.wiki/img/spells/scorch.png",
      },
      {
        id: "wall_of_fire",
        name: "Wall Of Fire",
        school: "Fire",
        level: "1 to 5",
        cooldown: "30s",
        mana: "30 to 50",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["4-8 AOE Damage", "13-25 Block Range"],
        description: "Recast to place anchor points, which erupts into a wall of fire when the cast finishes. This wall blocks projectiles and ignites creatures.",
        imageUrl: "https://iron.wiki/img/spells/wall_of_fire.png",
      },
    ],
  },
  {
    name: "Holy",
    color: schoolColors.Holy,
    spells: [
      {
        id: "angel_wing",
        name: "Angel Wing",
        school: "Holy",
        level: "1 to 5",
        cooldown: "120s",
        mana: "80 to 160",
        castType: "Instant",
        rarity: "Legendary",
        uniqueInfo: ["10s-50s Effect Length"],
        description: "Cast to gain wings made of holy energy, acting as an elytra, for a brief period of time.",
        imageUrl: "https://iron.wiki/img/spells/angel_wing.png",
      },
      {
        id: "blessing_of_life",
        name: "Blessing Of Life",
        school: "Holy",
        level: "1 to 10",
        cooldown: "10s",
        mana: "10 to 55",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-15 Healing"],
        description: "Cast to target any creature, showing a glowing outline. Completing the cast will heal this creature.",
        imageUrl: "https://iron.wiki/img/spells/blessing_of_life.png",
      },
      {
        id: "cleanse",
        name: "Cleanse",
        school: "Holy",
        level: "1",
        cooldown: "60s",
        mana: "100",
        castType: "Long",
        rarity: "Epic",
        uniqueInfo: ["3 Block Radius"],
        description: "Pray to a divine magic to cleanse yourself and nearby allies of harmful status effects.",
        imageUrl: "https://iron.wiki/img/spells/cleanse.png",
      },
      {
        id: "divine_smite",
        name: "Divine Smite",
        school: "Holy",
        level: "1 to 5",
        cooldown: "15s",
        mana: "30 to 90",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["8.0-20.0 Damage"],
        description: "With a fervor of holy energy, swing forth your weapon, doing a melee area attack. This spell is uninterruptible.",
        imageUrl: "https://iron.wiki/img/spells/divine_smite.png",
      },
      {
        id: "fortify",
        name: "Fortify",
        school: "Holy",
        level: "1 to 10",
        cooldown: "60s",
        mana: "80 to 170",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-15 Temporary HP", "8 Block Radius"],
        description: "Upon casting, fortify every friendly creature within a radius around you, giving them temporary HP.",
        imageUrl: "https://iron.wiki/img/spells/fortify.png",
      },
      {
        id: "greater_heal",
        name: "Greater Heal",
        school: "Holy",
        level: "1",
        cooldown: "45s",
        mana: "100",
        castType: "Long",
        rarity: "Rare",
        uniqueInfo: ["Max Healing"],
        description: "A more powerful but much slower version of heal, this spell will completely heal yourself upon being casted.",
        imageUrl: "https://iron.wiki/img/spells/greater_heal.png",
      },
      {
        id: "guiding_bolt",
        name: "Guiding Bolt",
        school: "Holy",
        level: "1 to 10",
        cooldown: "8s",
        mana: "20 to 65",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["3-7.5 Damage", "25s Effect Length"],
        description: "Fire a slow bolt of holy energy. Creatures hit will gain the Guided effect, homing nearby projectiles in towards them.",
        imageUrl: "https://iron.wiki/img/spells/guiding_bolt.png",
      },
      {
        id: "haste",
        name: "Haste",
        school: "Holy",
        level: "1 to 4",
        cooldown: "80s",
        mana: "50 to 80",
        castType: "Long",
        rarity: "Epic to Legendary",
        uniqueInfo: ["10%-40% Hastened", "30s-45s Effect", "5 Max Targets"],
        description: "In a radius around a targeted creature, apply the Hastened effect, increasing movement speed, attack speed, and mana regeneration.",
        imageUrl: "https://iron.wiki/img/spells/haste.png",
      },
      {
        id: "heal",
        name: "Heal",
        school: "Holy",
        level: "1 to 8",
        cooldown: "30s",
        mana: "30 to 135",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["5-12 Healing"],
        description: "Cast to infuse yourself with holy energy and immediately regain health.",
        imageUrl: "https://iron.wiki/img/spells/heal.png",
      },
      {
        id: "healing_circle",
        name: "Healing Circle",
        school: "Holy",
        level: "1 to 10",
        cooldown: "25s",
        mana: "40 to 130",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["0.5-2.75 AOE Healing", "5 Block Radius", "10s Duration"],
        description: "Around a targeted creature or block, place a stationary circle of holy magic that heals allies within.",
        imageUrl: "https://iron.wiki/img/spells/healing_circle.png",
      },
      {
        id: "sunbeam",
        name: "Sunbeam",
        school: "Holy",
        level: "1 to 10",
        cooldown: "20s",
        mana: "40 to 130",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["12-25.5 Damage"],
        description: "Funnel the power of the heavens into a beam of holy energy from above, smiting targets in an area.",
        imageUrl: "https://iron.wiki/img/spells/sunbeam.png",
      },
      {
        id: "wisp",
        name: "Wisp",
        school: "Holy",
        level: "1 to 10",
        cooldown: "3s",
        mana: "15 to 33",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["5-14 Damage"],
        description: "Conjure a projectile of holy energy that will float towards nearby targets and deal damage upon impact.",
        imageUrl: "https://iron.wiki/img/spells/wisp.png",
      },
    ],
  },
  {
    name: "Ice",
    color: schoolColors.Ice,
    spells: [
      {
        id: "cone_of_cold",
        name: "Cone Of Cold",
        school: "Ice",
        level: "1 to 10",
        cooldown: "12s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1.75-8.5 Damage"],
        description: "Hold to cast out a cone of cold energy, freezing creatures in its path.",
        imageUrl: "https://iron.wiki/img/spells/cone_of_cold.png",
      },
      {
        id: "frost_step",
        name: "Frost Step",
        school: "Ice",
        level: "1 to 8",
        cooldown: "12s",
        mana: "15 to 50",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10.5 Block Range"],
        description: "Cast to instantly teleport a short distance, leaving an explosion of ice behind that freezes and damages creatures.",
        imageUrl: "https://iron.wiki/img/spells/frost_step.png",
      },
      {
        id: "frostbite",
        name: "Frostbite",
        school: "Ice",
        level: "1 to 10",
        cooldown: "1s",
        mana: "10 to 28",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Shoot a small projectile of ice forward, freezing whatever it hits.",
        imageUrl: "https://iron.wiki/img/spells/frostbite.png",
      },
      {
        id: "ice_block",
        name: "Ice Block",
        school: "Ice",
        level: "1 to 5",
        cooldown: "60s",
        mana: "80 to 160",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["5s-25s Duration"],
        description: "Encase yourself in a block of ice, making you invulnerable but immobile for a duration. The block can be broken early.",
        imageUrl: "https://iron.wiki/img/spells/ice_block.png",
      },
      {
        id: "ice_spikes",
        name: "Ice Spikes",
        school: "Ice",
        level: "1 to 10",
        cooldown: "15s",
        mana: "30 to 75",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["6-15 Damage", "8 Block Range"],
        description: "Summon a line of ice spikes from the ground, damaging and knocking up enemies in their path.",
        imageUrl: "https://iron.wiki/img/spells/ice_spikes.png",
      },
      {
        id: "ice_tomb",
        name: "Ice Tomb",
        school: "Ice",
        level: "1 to 5",
        cooldown: "30s",
        mana: "60 to 120",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["4s-8s Freeze Duration"],
        description: "Encase a target in a tomb of ice, freezing them in place and making them vulnerable to attacks.",
        imageUrl: "https://iron.wiki/img/spells/ice_tomb.png",
      },
      {
        id: "icicle",
        name: "Icicle",
        school: "Ice",
        level: "1 to 10",
        cooldown: "8s",
        mana: "40 to 85",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10-19 Damage"],
        description: "Hold to charge a piercing icicle. This icicle pierces through targets and travels straight.",
        imageUrl: "https://iron.wiki/img/spells/icicle.png",
      },
      {
        id: "ray_of_frost",
        name: "Ray Of Frost",
        school: "Ice",
        level: "1 to 10",
        cooldown: "12s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1-7.75 Damage"],
        description: "Hold to cast a focused beam of cold energy, damaging and freezing targets in its path.",
        imageUrl: "https://iron.wiki/img/spells/ray_of_frost.png",
      },
      {
        id: "snowball",
        name: "Snowball",
        school: "Ice",
        level: "1 to 10",
        cooldown: "3s",
        mana: "15 to 42",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["4-10 Damage", "3 Block AOE"],
        description: "Throw a giant snowball that explodes on impact, freezing and damaging enemies in the area.",
        imageUrl: "https://iron.wiki/img/spells/snowball.png",
      },
      {
        id: "summon_polar_bear",
        name: "Summon Polar Bear",
        school: "Ice",
        level: "1 to 5",
        cooldown: "150s",
        mana: "75 to 135",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["1 Summon"],
        description: "Conjure a friendly polar bear to fight alongside you. The bear's stats scale with spell power.",
        imageUrl: "https://iron.wiki/img/spells/summon_polar_bear.png",
      },
    ],
  },
  {
    name: "Lightning",
    color: schoolColors.Lightning,
    spells: [
      {
        id: "ascension",
        name: "Ascension",
        school: "Lightning",
        level: "1 to 5",
        cooldown: "60s",
        mana: "50 to 130",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10s-30s Effect Length"],
        description: "Cast to empower yourself with electricity, gaining levitation and electrifying nearby creatures.",
        imageUrl: "https://iron.wiki/img/spells/ascension.png",
      },
      {
        id: "ball_lightning",
        name: "Ball Lightning",
        school: "Lightning",
        level: "1 to 10",
        cooldown: "10s",
        mana: "25 to 70",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["3-9 Damage", "5-10 Bounces"],
        description: "Launch a ball of lightning that bounces between surfaces and enemies, dealing damage with each hit.",
        imageUrl: "https://iron.wiki/img/spells/ball_lightning.png",
      },
      {
        id: "chain_lightning",
        name: "Chain Lightning",
        school: "Lightning",
        level: "1 to 10",
        cooldown: "12s",
        mana: "35 to 80",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["5-14 Damage", "3-8 Chain Targets"],
        description: "Shoot a bolt of lightning that chains between multiple targets, dealing damage to each.",
        imageUrl: "https://iron.wiki/img/spells/chain_lightning.png",
      },
      {
        id: "charge",
        name: "Charge",
        school: "Lightning",
        level: "1 to 5",
        cooldown: "25s",
        mana: "40 to 80",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["8-20 Damage", "12-20 Block Range"],
        description: "Dash forward in a bolt of lightning, damaging all creatures in your path.",
        imageUrl: "https://iron.wiki/img/spells/charge.png",
      },
      {
        id: "electrocute",
        name: "Electrocute",
        school: "Lightning",
        level: "1 to 10",
        cooldown: "8s",
        mana: "20 to 56",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["4-13 Damage"],
        description: "Electrocute a target, dealing lightning damage and briefly stunning them.",
        imageUrl: "https://iron.wiki/img/spells/electrocute.png",
      },
      {
        id: "lightning_bolt",
        name: "Lightning Bolt",
        school: "Lightning",
        level: "1 to 10",
        cooldown: "1s",
        mana: "10 to 28",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Shoot a bolt of lightning forward that travels instantly to its target.",
        imageUrl: "https://iron.wiki/img/spells/lightning_bolt.png",
      },
      {
        id: "lightning_lance",
        name: "Lightning Lance",
        school: "Lightning",
        level: "1 to 10",
        cooldown: "8s",
        mana: "40 to 85",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["10-28 Damage"],
        description: "Hold to charge a devastating lance of lightning that pierces through enemies.",
        imageUrl: "https://iron.wiki/img/spells/lightning_lance.png",
      },
      {
        id: "shockwave",
        name: "Shockwave",
        school: "Lightning",
        level: "1 to 5",
        cooldown: "20s",
        mana: "60 to 100",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["8-16 Damage", "4-8 Block Radius"],
        description: "Release a shockwave of electricity around you, damaging and stunning nearby creatures.",
        imageUrl: "https://iron.wiki/img/spells/shockwave.png",
      },
      {
        id: "thunderstorm",
        name: "Thunderstorm",
        school: "Lightning",
        level: "1 to 5",
        cooldown: "45s",
        mana: "80 to 160",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["4-10 Damage", "10s-20s Duration", "8 Block Radius"],
        description: "Summon a thunderstorm in a targeted area, randomly striking creatures with lightning for a duration.",
        imageUrl: "https://iron.wiki/img/spells/thunderstorm.png",
      },
      {
        id: "volt_strike",
        name: "Volt Strike",
        school: "Lightning",
        level: "1 to 8",
        cooldown: "1s",
        mana: "15 to 36",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["4-8.5 Damage", "Stun Effect"],
        description: "Strike with electrified claws, dealing lightning damage and briefly stunning the target.",
        imageUrl: "https://iron.wiki/img/spells/volt_strike.png",
      },
    ],
  },
  {
    name: "Nature",
    color: schoolColors.Nature,
    spells: [
      {
        id: "blight",
        name: "Blight",
        school: "Nature",
        level: "1 to 10",
        cooldown: "25s",
        mana: "50 to 100",
        castType: "Long",
        rarity: "Common to Legendary",
        uniqueInfo: ["15%-40% Reduced Armor", "10s-20s Effect", "6.5-9 Block Radius"],
        description: "Curse an area with blight, reducing the armor of all creatures within and dealing poison damage over time.",
        imageUrl: "https://iron.wiki/img/spells/blight.png",
      },
      {
        id: "earthquake",
        name: "Earthquake",
        school: "Nature",
        level: "1 to 5",
        cooldown: "30s",
        mana: "80 to 160",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["6-14 Damage", "6-10 Block Radius"],
        description: "Shake the earth violently, damaging and knocking down all creatures in a large radius around you.",
        imageUrl: "https://iron.wiki/img/spells/earthquake.png",
      },
      {
        id: "firefly_swarm",
        name: "Firefly Swarm",
        school: "Nature",
        level: "1 to 10",
        cooldown: "3s",
        mana: "15 to 42",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["3-8 Fireflies", "2-5 Damage"],
        description: "Release a swarm of magical fireflies that seek out and damage nearby enemies.",
        imageUrl: "https://iron.wiki/img/spells/firefly_swarm.png",
      },
      {
        id: "oakskin",
        name: "Oakskin",
        school: "Nature",
        level: "1 to 5",
        cooldown: "60s",
        mana: "50 to 90",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["20%-50% Damage Reduction", "10s-25s Duration"],
        description: "Encase yourself in bark armor, significantly reducing incoming damage for a duration.",
        imageUrl: "https://iron.wiki/img/spells/oakskin.png",
      },
      {
        id: "poison_arrow",
        name: "Poison Arrow",
        school: "Nature",
        level: "1 to 10",
        cooldown: "8s",
        mana: "40 to 85",
        castType: "Long",
        rarity: "Rare to Legendary",
        uniqueInfo: ["8-17 Damage", "Poison Effect"],
        description: "Fire an arrow tipped with deadly poison that deals damage over time to struck targets.",
        imageUrl: "https://iron.wiki/img/spells/poison_arrow.png",
      },
      {
        id: "poison_breath",
        name: "Poison Breath",
        school: "Nature",
        level: "1 to 10",
        cooldown: "12s",
        mana: "5 to 14",
        castType: "Continuous",
        rarity: "Common to Legendary",
        uniqueInfo: ["1-7.75 Damage"],
        description: "Hold to breathe out a cone of poison, damaging and poisoning creatures in its path.",
        imageUrl: "https://iron.wiki/img/spells/poison_breath.png",
      },
      {
        id: "poison_splash",
        name: "Poison Splash",
        school: "Nature",
        level: "1 to 10",
        cooldown: "1s",
        mana: "10 to 28",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["6-10.5 Damage"],
        description: "Throw a splash of poison forward that damages and poisons whatever it hits.",
        imageUrl: "https://iron.wiki/img/spells/poison_splash.png",
      },
      {
        id: "root",
        name: "Root",
        school: "Nature",
        level: "1 to 10",
        cooldown: "35s",
        mana: "45 to 72",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["5s-14s Effect Length"],
        description: "Around a targeted creature, sprout magical roots that entangle them and completely prevent non-magical movement.",
        imageUrl: "https://iron.wiki/img/spells/root.png",
      },
      {
        id: "spider_aspect",
        name: "Spider Aspect",
        school: "Nature",
        level: "1 to 8",
        cooldown: "90s",
        mana: "35 to 70",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["5%-40% Additional Poisoned Damage", "20s-55s Effect Length"],
        description: "Instill yourself with poisonous magic, dealing additional melee, ranged, or spell damage to creatures that are poisoned.",
        imageUrl: "https://iron.wiki/img/spells/spider_aspect.png",
      },
      {
        id: "stomp",
        name: "Stomp",
        school: "Nature",
        level: "1 to 5",
        cooldown: "16s",
        mana: "50 to 90",
        castType: "Long",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["8-16 Damage", "5-9 Block Range"],
        description: "With a magic force, stomp the ground in front of you and send a short tremor forward through the ground, damaging creatures in its path.",
        imageUrl: "https://iron.wiki/img/spells/stomp.png",
      },
      {
        id: "touch_dig",
        name: "Touch Dig",
        school: "Nature",
        level: "1 to 3",
        cooldown: "0s",
        mana: "15 to 15",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["Iron Harvest Level", "8 Block Range"],
        description: "Use magic to break a block. Held items affect drops.",
        imageUrl: "https://iron.wiki/img/spells/touch_dig.png",
      },
      {
        id: "acid_orb",
        name: "Acid Orb",
        school: "Nature",
        level: "1 to 10",
        cooldown: "3s",
        mana: "20 to 56",
        castType: "Instant",
        rarity: "Common to Legendary",
        uniqueInfo: ["5-14 Damage", "Armor Reduction"],
        description: "Launch an orb of corrosive acid that damages and reduces the armor of creatures it hits.",
        imageUrl: "https://iron.wiki/img/spells/acid_orb.png",
      },
      {
        id: "gluttony",
        name: "Gluttony",
        school: "Nature",
        level: "1 to 5",
        cooldown: "30s",
        mana: "40 to 80",
        castType: "Instant",
        rarity: "Rare to Legendary",
        uniqueInfo: ["15%-35% Max HP Heal", "Food Consumption"],
        description: "Consume food items from your inventory to rapidly heal yourself based on the nutritional value consumed.",
        imageUrl: "https://iron.wiki/img/spells/gluttony.png",
      },
      {
        id: "spiderweb",
        name: "Spiderweb",
        school: "Nature",
        level: "1 to 5",
        cooldown: "15s",
        mana: "30 to 60",
        castType: "Instant",
        rarity: "Uncommon to Legendary",
        uniqueInfo: ["3-7 Block Radius", "5s-12s Duration"],
        description: "Shoot a web projectile that creates a sticky web area, slowing and trapping creatures caught within.",
        imageUrl: "https://iron.wiki/img/spells/spiderweb.png",
      },
    ],
  },
];

export function getAllSpells(): Spell[] {
  return spellSchools.flatMap((school) => school.spells);
}

export function getSpellsBySchool(schoolName: string): Spell[] {
  const school = spellSchools.find((s) => s.name === schoolName);
  return school?.spells || [];
}

export function searchSpells(query: string): Spell[] {
  const lowerQuery = query.toLowerCase();
  return getAllSpells().filter(
    (spell) => spell.name.toLowerCase().includes(lowerQuery)
  );
}

export function getSchoolColor(schoolName: string): string {
  return schoolColors[schoolName] || "hsl(0 0% 50%)";
}
